Feature/product cud
itbook-store/itbook-shop pull request #56
Opened 2023-01-07 18:11 UTC by yihoney

다 못했지만 우선 올립니다 ....

2023-01-07 20:35 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/controller/ProductRestController.java
> + * 상품 컨트롤러 클래스입니다.
스프링에서 제공하는 mvc의 컨트롤러의 개념을 모르는 사람이 봐도 이해할수 있도록
몇 단어만 더 추가하면 좋지않을까요? :)

2023-01-07 20:43 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/controller/ProductRestController.java
> +    @PostMapping("/api/products")
모든 메서드에 항상 동일할 /api/products 는 @RequestMapping을 사용하는 것이 편하지 않으실까요?

2023-01-07 20:46 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/dto/request/AddProductRequestDto.java
> +    private Integer stock;
부가세 같은 경우에 최소값을 지정해주면 허위값으로부터 방어가 가능하지 않을까요?

2023-01-07 20:47 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/dto/request/AddProductRequestDto.java
> +    private String simpleDescription;
String인 경우에는 @NotBlank를 쓰면 Notnull과 빈문자열, 공백하나를 방어할수 있어요:)

2023-01-07 20:50 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/controller/ProductRestController.java
> +        if (bindingResult.hasErrors()) {
bindingResult로 처리하는 것도 좋지만 매번 중복 로직이 발생하니 advisor에서 처리하는 건 어떨까요? 이건 조금있다가 팀원들과 다같이 얘기해봐요

2023-01-07 20:51 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/controller/ProductRestController.java
> +        MultiValueMap<String, String> headers = new LinkedMultiValueMap<>();
헤더에 뭔가 값을 넣어주는 용도로 header를 만드신것 같지만 그냥 깡통 헤더를 넣으시는군요!
이럴거면 ResponseEntity.status() 를 이용해보시는건 어떨까요? header가 없을때 용이하게 사용가능해요:)

2023-01-07 20:54 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/dto/response/AddProductResponseDto.java
> +            throw new IllegalArgumentException("productNo is null");
IllegalArgumentException 같은 경우에는 예외를 커스톰해서 조금더 가독성을 높여보는건 어떨까요?

2023-01-07 20:55 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/service/ProductService.java
> +    @Transactional
여기에 @Transactional은 어떤 이유로 붙이셨을까요?

2023-01-07 20:57 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/controller/ProductRestController.java
> +    public ResponseEntity<AddProductResponseDto> productAdd(
https://cocobi.tistory.com/27 코드컨벤션 규칙 정할때 메소드명을 통일하기로 했어요.
productSave()로 변경해 보시는건 어떨까요?

2023-01-07 20:59 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/service/ProductServiceImpl.java
> +    @Override
조회영역에서는 @Transactional을 안붙이신거 보니 readOnly 개념을 잘 이해하고 계신것 같아요:)

2023-01-07 21:03 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/dto/response/AddProductResponseDto.java
> +    @JsonProperty("product_no")
이부분은 json을 어떻게 rest api 설계하셨는지에 따라 달라질거 같아요.
우리팀원들은 간편하게 productNo로 해버리면 이런 코드가 추가되지 않아도 돼서 편하지 않을까요? 하늬님 의견이 궁금하군요

2023-01-07 21:04 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/dto/response/AddProductResponseDto.java
> +    public static AddProductResponseDto getInstance(Long productNo) {
두번다시 재사용될일 없는 코드를 싱글톤패턴으로 만드신 이유가 있으실까요?

2023-01-07 21:05 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/dto/response/AddProductResponseDto.java
> +            throw new IllegalArgumentException("productNo is null");
널체크를 여기서 하는 건 좋은것 같아요

2023-01-07 21:07 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/service/ProductServiceImpl.java
> +        productRepository.save(product);
save가 안되었다면 예외가 발생했을테고 그렇지 않았다면 성공했을텐데 null체크를 한번더 할 필요가 있을까요?
정말 호기심에 궁금해서 물어봐요.

2023-01-07 21:09 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/controller/ProductRestController.java
> +        return ResponseEntity.ok().build();
코드컨벤션에서 삭제성공하면 204를 보내기로 했어요!
https://nhnacademy.dooray.com/project/3437067340287111583/3437903264342654062?contentsType=contents&query=all%3D%25EC%25BB%25A8%25EB%25B2%25A4%25EC%2585%2598 참고해주세요

2023-01-07 21:10 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/dto/request/ModifyProductRequestDto.java
> +
addrequest와 modify가 현재상황에서 12개 필드로 서로 같아보이는데 같이 써보는건 어떨까요?

2023-01-07 21:11 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/service/ProductServiceImpl.java
> +        return AddProductResponseDto.getInstance(product.getProductNo());
이건 save가 안되었다면 예외가 발생했을테고 그렇지 않았다면 성공했을텐데 null체크를 한번더 할 필요가 있을까요? 정말 호기심에 궁금해서 물어봐요.

2023-01-07 21:13 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/service/ProductServiceImpl.java
> +        productRepository.save(product);
modify를 할때는 jpa에서 제공하는 dirty-check 변경감지 기술을 이용해봐요 미리 만들어놓은 쿼리가 있기때문에 쿼리 캐싱효과를 누릴수 있어요.

2023-01-07 21:15 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/controller/ProductRestController.java
> +            return ResponseEntity.badRequest().build();
삭제실패시 실패 메세지도 함께 보내주는건 어떨까요? 또 삭제했을때 실패한 이유가 badRequest만 있지는 않을거잖아요?
각시점에 맞게 확인하고 throw로 처리하는게 편할수 있을 것도 같아요:)

2023-01-07 21:17 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/repository/ProductRepository.java
> +    Optional<Product> findByProductNo(Long productNo);
ProductNo는 식별키 아닌가요?
findById라고 제공되는 jpa 메서드를 써도 괜찮을 것 같아요:)

2023-01-07 21:17 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/repository/ProductRepository.java
> +    void deleteByProductNo(Long productNo);
여기도 마찬가지 ^_^

2023-01-07 21:18 UTC, jun1718 commented on src/test/java/shop/itbook/itbookshop/productgroup/product/controller/ProductRestControllerTest.java
> +    void setUp() {
테스트를 열심히하셨군요

2023-01-07 21:18 UTC, jun1718 requested changes
말한부분 체크한번 해주시면 감사할것 같아요:) 고생하셨어요.

2023-01-08 01:57 UTC, jun1718 commented on src/main/java/shop/itbook/itbookshop/productgroup/product/controller/ProductRestController.java
> +            return ResponseEntity.badRequest().build();
삭제시에는 메세지 없이 상태값만 보내기로 했었는데 새벽에 제가잠시 이상한생각을 한것같군요

2023-01-09 00:34 UTC, jun1718 approved these changes

2023-01-09 00:34 UTC, JeongJaew0n approved these changes
고생하셨습니다

2023-01-09 00:35 UTC, merged